package com.inspiredandroid.kai.ui.settings

/**
 * Languages the app ships translations for, shown in Settings → General → Language.
 * Tags follow the values-* resource dirs (legacy codes `in`/`iw` included, matching
 * Android's locale resolution); display names are native on purpose — someone who
 * can't read the current UI language must still recognize their own.
 */
internal val APP_LANGUAGES: List<Pair<String, String>> = listOf(
    "af" to "Afrikaans",
    "am" to "አማርኛ",
    "ar" to "العربية",
    "be" to "Беларуская",
    "bg" to "Български",
    "bn" to "বাংলা",
    "cs" to "Čeština",
    "da" to "Dansk",
    "de" to "Deutsch",
    "el" to "Ελληνικά",
    "es" to "Español",
    "et" to "Eesti",
    "fa" to "فارسی",
    "fi" to "Suomi",
    "fil" to "Filipino",
    "fr" to "Français",
    "gu" to "ગુજરાતી",
    "hi" to "हिन्दी",
    "hr" to "Hrvatski",
    "hu" to "Magyar",
    "in" to "Bahasa Indonesia",
    "it" to "Italiano",
    "iw" to "עברית",
    "ja" to "日本語",
    "kk" to "Қазақша",
    "ko" to "한국어",
    "lt" to "Lietuvių",
    "lv" to "Latviešu",
    "mr" to "मराठी",
    "ms" to "Bahasa Melayu",
    "nb" to "Norsk bokmål",
    "nl" to "Nederlands",
    "pa" to "ਪੰਜਾਬੀ",
    "pl" to "Polski",
    "pt" to "Português",
    "rm" to "Rumantsch",
    "ro" to "Română",
    "ru" to "Русский",
    "sk" to "Slovenčina",
    "sl" to "Slovenščina",
    "sq" to "Shqip",
    "sr" to "Српски",
    "sv" to "Svenska",
    "sw" to "Kiswahili",
    "ta" to "தமிழ்",
    "te" to "తెలుగు",
    "th" to "ไทย",
    "tr" to "Türkçe",
    "uk" to "Українська",
    "ur" to "اردو",
    "vi" to "Tiếng Việt",
    "zh" to "中文",
    "zh-rTW" to "繁體中文",
    "zu" to "isiZulu",
)
